export { default as HomeContent } from './Contents/HomeContent'
export { default as GetStartedForm } from './Forms/GetStartedForm'
export { default as RegisterForm } from './Forms/RegisterForm'
export { default as Faq } from './Faq'
export { default as CookiePreferences } from './CookiePreferences'
export { default as Footer } from './Footer'